# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: publication
    weight: 10
  - name: Projects
    url: projects
    weight: 20   
  - name: Teaching
    url: teaching
    weight: 30   
  - name: News
    url: post
    weight: 40
  - name: Team
    url: people
    weight: 50
  - name: Talks & Events
    url: event
    weight: 60
  - name: Contact
    url: contact
    weight: 70
